
all: hello share_private schedule_example

hello: hello.cpp
	g++ hello.cpp -fopenmp -o hello
share_private: share_private.cpp
	g++ share_private.cpp -fopenmp -o share_private
schedule_example: schedule.cpp
	g++ schedule.cpp -fopenmp -o schedule_example
