
all: hello test_gprof test_gprof1

test_gprof: test_gprof.cpp
	g++ test_gprof.cpp -o test_gprof

test_gprof1: test_gprof1.cpp
	g++ test_gprof1.cpp -o test_gprof1

hello: hello.cpp
	g++ hello.cpp -o hello
	
clean:
	rm test_gprof
	
