#!/bin/bash

CC="gcc"
CFLAGS="-O1 -std=c11 -fopenmp"

set -ex

$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=1  -DDEF_GEN_RANDOM_LIST mem.c -o ./bin/mem
$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=2  -DDEF_GEN_RANDOM_LIST mem.c -o ./bin/mem_chain2
$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=4  -DDEF_GEN_RANDOM_LIST mem.c -o ./bin/mem_chain4
$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=6  -DDEF_GEN_RANDOM_LIST mem.c -o ./bin/mem_chain6
$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=8  -DDEF_GEN_RANDOM_LIST mem.c -o ./bin/mem_chain8
$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=10 -DDEF_GEN_RANDOM_LIST mem.c -o ./bin/mem_chain10
$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=12 -DDEF_GEN_RANDOM_LIST mem.c -o ./bin/mem_chain12
$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=14 -DDEF_GEN_RANDOM_LIST mem.c -o ./bin/mem_chain14
$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=16 -DDEF_GEN_RANDOM_LIST mem.c -o ./bin/mem_chain16


$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=1 -DDEF_GEN_SEQUENTIAL_LIST mem.c -o ./bin/mem_address_ordered_traveral

$CC $CFLAGS -DDEF_CHAIN_COUNT=1 -DDEF_GEN_RANDOM_LIST -DDEF_RANDOM_WITHOUT_PTRCHASE mem.c -o ./bin/mem_random_without_ptrchase
$CC $CFLAGS -DDEF_CHAIN_COUNT=1 -DDEF_GEN_SEQUENTIAL_LIST -DDEF_SEQENTIAL_WITHOUT_PTRCHASE mem.c -o ./bin/mem_seqential_without_ptrchase


$CC $CFLAGS -DDEF_PTRCHASE -DDEF_CHAIN_COUNT=1  -DDEF_GEN_RANDOM_LIST -DDEF_PREFETCH mem.c -o ./bin/mem_prefetch
